# Generated by Django 2.0.5 on 2018-05-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_mainshow_shop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshow',
            table='axf_mainshow',
        ),
    ]
