# Generated by Django 2.0.5 on 2018-05-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180522_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
