# Generated by Django 2.0.5 on 2018-05-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_order_ordergoods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='axf_cart',
        ),
    ]
